export { SearchField } from './ui/SearchField'
export type { SearchFieldProps } from './ui/SearchField'
export { ProductResults } from './ui/ProductResults'
export type { ProductResultsProps } from './ui/ProductResults'
export { PreorderLinks } from './ui/PreorderLinks'
export type { PreorderLinksProps } from './ui/PreorderLinks'
export { useRecentSearches } from './lib/useRecentSearches'
export { toKeyword } from './lib/toKeyword'
export { ONGOING_PREORDERS, POPULAR_KEYWORDS } from './model/searchSuggestions'
// 검색창·검색 결과 위젯이 같은 어두운 검색 화면 스타일을 쓴다.
export * as searchStyles from './ui/search.css'
